Add kfp pipeline for running a pytorch job
opendatahub-io/ilab-on-ocp pull request #14
Opened 2024-09-06 18:58 UTC by Shreyanand

This PR adds the kfp pipeline for launching the Instructlab train Pytorch job. It is based on the kfp pytorch launcher [component](https://github.com/kubeflow/pipelines/tree/master/components/kubeflow/pytorch-launcher). However that component is 3 years old and I had to make some changes for it to work. 

In the current state, the pipeline works- kfp workflow triggers a pytorch job. However it is not able to run multinode training yet. Fixes found in #10 should make this run completely. 

One caveat with the current launcher is that it does not have a way to run the pytorch job with just the master node. It has to have a worker node. That is not a limitation of a vanilla pytorch job. 

Putting it in draft for now but it can be tested if curious.

2024-09-06 20:15 UTC, cooktheryan commented
@tumido do you want to review this in the current state and @MichaelClifford maybe Monday we pair this with Tom's PR and start generating the MVP run

2024-09-09 12:07 UTC, tumido approved these changes
Can we please remove the `create_worker_spec` component? It seems to be unnecessary here.

2024-09-09 12:07 UTC, tumido commented on training/pipeline.py
> +                            },
Should we parametrize this?

2024-09-09 12:07 UTC, tumido requested changes
Wrong button 😄  I've meant to request changes... 😄

2024-09-09 13:10 UTC, tumido requested changes

2024-09-09 13:10 UTC, tumido commented on training/pipeline.py
> +    import kfp.compiler as compiler
I don't think you need to nest the import here. This is against https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/import-outside-toplevel.html

2024-09-09 13:10 UTC, tumido commented on training/pipeline.py
> +    )
This is somewhat weirdly formatted. I think simple:


```suggestion
    pipeline_file = "pipeline.yaml"
    print(f"Compiling pipeline as {pipeline_file}")
    compiler.Compiler().compile(ilab_train, pipeline_file)
```

Would be fully compliant with PEP8.

2024-10-03 16:06 UTC, leseb commented
Please install https://docs.astral.sh/ruff/installation/ on your system and run `ruff format .` once https://github.com/redhat-et/ilab-on-ocp/pull/57 is merged. THEN rebase your PR, everything should go fine :).

2024-12-04 02:54 UTC, Shreyanand commented
Closing in favour of #231

2024-12-04 02:54 UTC, closed without merging