feat: add tls support for sdg teacher model
opendatahub-io/ilab-on-ocp pull request #166
Opened 2024-11-07 21:40 UTC by HumairAK

Adds tls support for SDG teacher model. 

Implementation is very similar to how certs are passed in for the judge server model. Note that each model can be served in different locations/clusters, so we require configurable bundles for each (i.e. they can't share it).

2024-11-12 19:32 UTC, gmfrasca reviewed
Tested and verified against an model that required TLS certs - previously did not work before this change but now does when providing the appropriate secret and keyname via `--sdg-serving-model-ca-cert` and `--sdg-serving-model-ca-cert-cm-key`

/lgtm

2024-11-13 08:48 UTC, leseb requested changes

2024-11-14 16:08 UTC, HumairAK commented on standalone/standalone.py
> +                    sdg_serving_model_ca_cert = secret.data.get("SDG_CA_CERT")
yes, good catch, fixed!

2024-11-14 16:29 UTC, HumairAK commented on standalone/README.md
>    true). `SDG_OBJECT_STORE_VERIFY_TLS` environment variable can be used as well. **Optional**
I had not originally added these as env var, but I've updated that as well, see [here](https://github.com/opendatahub-io/ilab-on-ocp/pull/166/files#diff-adba7904639f6992630ac0fea4405d44b221fc89374ba47fbca676aad09c9aabR817-R829)

2024-11-14 16:33 UTC, HumairAK commented on standalone/standalone.py
> +                ]
fyi @leseb / @gmfrasca  

added this update since `.env` is immutable

2024-11-15 19:52 UTC, HumairAK commented on standalone/README.md
>    true). `SDG_OBJECT_STORE_VERIFY_TLS` environment variable can be used as well. **Optional**
@leseb can you clarify a bit more, are you saying for the descriptions for 


```
* `--sdg-serving-model-ca-cert`: Name of the Kubernetes ConfigMap containing the SDG serving model CA cert.
  `SDG_SERVING_MODEL_CA_CERT` environment variable can be used as well. **Optional**
* `--sdg-serving-model-ca-cert-cm-key`: Name of the Key in the Kubernetes ConfigMap containing the SDG serving model CA cert.
  `SDG_SERVING_MODEL_CA_CERT_CM_KEY` environment variable can be used as well. **Optional**
```

You would also like us to mention that these can be specified using `SDG_CA_CERT` and `SDG_CA_CERT_CM_KEY` keys when using `--sdg-serving-model-secret` ?

2024-11-15 19:56 UTC, HumairAK commented on standalone/README.md
>    true). `SDG_OBJECT_STORE_VERIFY_TLS` environment variable can be used as well. **Optional**
Nevermind, I think you mean this: https://github.com/opendatahub-io/ilab-on-ocp/pull/166/commits/4599472aacb5db53250699e815697fd88b3b349c 

Is that correct?

2024-11-19 20:09 UTC, MichaelClifford approved these changes
LGTM!

2024-11-19 20:17 UTC, merged